import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between">
          <div>
            <Link href={'/'}>Shop</Link>
            <Link href={'/'}>Contact</Link>
          </div>
          <div>
            <Link href={'/'}>Sign in</Link>
            <Link href={'/'}>Cart</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
